version: '3.9'
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
