[tool.black]
line-length = 100
target-version = ["py311"]
exclude = '''
/(
  \.git
 | \.venv
 | build
 | dist
)/
'''

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I"]
ignore = []
exclude = ["build", "dist", ".venv", ".git"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = "tests"

