[tool.black]
line-length = 100
target-version = ["py311"]
exclude = '''
/(
  \.git
 | \.venv
 | build
 | dist
)/
'''

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I"]
ignore = []
exclude = ["build", "dist", ".venv", ".git"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
show_error_codes = true
ignore_missing_imports = true
exclude = ["build", "dist", ".venv", ".git"]

[tool.bandit]
exclude_dirs = ["tests", "build", "dist", ".venv", ".git"]
skips = ["B101", "B601"]  # Skip assert checks and shell usage

[tool.pytest.ini_options]
asyncio_mode = "auto"
timeout = 30
timeout_method = "thread"

